### ISSUE TITLE
Model download link is invalid

### ISSUE THREAD

**Issue by Rp12138** [zjysteven/PrivayAttack_AT_FL#1]
Hello, I see that the model download link seems to be invalid. Can you update it? In addition, I noticed that your code contains experiments related to the mobilenet model. Can your method be successfully applied to this model?

**Comment by zjysteven** [comment]
Hi, earlier I was using the adversarially pre-trained models provided by this paper https://arxiv.org/pdf/2007.08489v2.pdf, whose github repo was https://github.com/microsoft/robust-models-transfer, but somehow the repo has gone now, which is why the download links don't work anymore. You can try some alternative pre-trained models provided by https://github.com/MadryLab/robustness?tab=readme-ov-file#pretrained-models.

I don't remember conducting experiments on mobilenet, but the method is agnostic to model architecture, so I would expect it can be successfully applied to mobilenet as well.

**Comment by Rp12138** [comment]
您的邮件已成功发送给任鹏QQ号为1348308163

**Comment by zjysteven** [comment]
Closing for now. Feel free to reopen if you have any other questions.
